[advisories]
yanked = "deny"
unmaintained = "all"
unsound = "all"

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = [
  "openssl",
  "openssl-sys",
]

[bans.workspace-dependencies]
duplicates = "deny"
include-path-dependencies = true
unused = "deny"

[licenses]
allow = [
    "MIT",
    "AGPL-3.0-only",
    "Apache-2.0",
    "ISC",
    "Zlib",
    "CC0-1.0",
    "BSD-3-Clause",
    "Unicode-3.0",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
