[toolchain]
channel = "nightly-2026-09-12"
components = ["rust-src", "rustfmt", "clippy"]
targets = ["i686-unknown-linux-musl", "x86_64-unknown-linux-musl", "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-musl"]
