[package]
name = "bubblebox"
description = "Painless cross-platform sandboxing"
version = "0.0.0"
authors = ["superwhiskers <whiskerdev@protonmail.com>"]
repository = "https://git.errno.systems/layer-cake"
# TODO: should get its own readme once more complete
readme = "../../readme.md"
edition = "2024"
license = "AGPL-3.0-only"

[dependencies]
rustix.workspace = true
thiserror.workspace = true
seccompiler.workspace = true
libc.workspace = true
linux-raw-sys.workspace = true
itoa.workspace = true
rkyv.workspace = true
scopeguard.workspace = true

[dependencies.dbus]
workspace = true
optional = true

[dependencies.uuid]
workspace = true
optional = true

[features]
default = ["systemd-cgroups"]

# Adds support for automatically acquiring a part of the cgroups hierarchy
# through systemd
systemd-cgroups = ["dep:dbus", "dep:uuid"]

[lints]
workspace = true
