[package]
name = "layer-cake-modrinth"
description = "Modrinth resource provider for the layer cake Minecraft launcher"
version = "0.0.0"
authors = ["superwhiskers <whiskerdev@protonmail.com>"]
repository = "https://git.errno.systems/layer-cake"
readme = "../../readme.md"
edition = "2024"
license = "AGPL-3.0-only"

[dependencies]
http.workspace = true
hyper-rustls.workspace = true
tracing.workspace = true
simd-json.workspace = true
hyper.workspace = true
simd-json-derive.workspace = true

[lints]
workspace = true
