[package]
name = "layer-cake-core"
description = "Primitives for the layer cake Minecraft launcher"
version = "0.0.0"
authors = ["superwhiskers <whiskerdev@protonmail.com>"]
repository = "https://git.errno.systems/layer-cake"
readme = "../../readme.md"
edition = "2024"
license = "AGPL-3.0-only"

[dependencies]
tracing.workspace = true
futures.workspace = true
tokio.workspace = true

[lints]
workspace = true
